# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 00:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe5\x90\x8d\xe7\xa7\xb0')),
                ('code', models.CharField(max_length=50, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe7\xbc\x96\xe5\x8f\xb7')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe7\xab\xa0\xe8\x8a\x82\xe5\x90\x8d\xe7\xa7\xb0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_contents.CourseInfo', verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u7ae0\u8282',
                'verbose_name_plural': '\u8bfe\u7a0b\u7ae0\u8282',
            },
        ),
        migrations.CreateModel(
            name='ResourceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe8\xb5\x84\xe6\xba\x90\xe5\x90\x8d\xe7\xa7\xb0')),
                ('code', models.CharField(max_length=50, verbose_name=b'\xe8\xb5\x84\xe6\xba\x90\xe7\xbc\x96\xe5\x8f\xb7')),
                ('format', models.IntegerField(choices=[(b'1', b'\xe8\xa7\x86\xe9\xa2\x91'), (b'2', b'h5\xe8\xb5\x84\xe6\xba\x90\xe5\x8c\x85')], verbose_name=b'\xe8\xb5\x84\xe6\xba\x90\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('download', models.FileField(max_length=200, upload_to=b'resource/%Y/%m', verbose_name=b'\xe8\xb5\x84\xe6\xba\x90\xe6\x96\x87\xe4\xbb\xb6')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u8d44\u6e90\u6587\u4ef6',
                'verbose_name_plural': '\u8d44\u6e90\u6587\u4ef6',
            },
        ),
        migrations.AddField(
            model_name='coursesection',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs_contents.ResourceInfo', verbose_name=b'\xe8\xb5\x84\xe6\xba\x90'),
        ),
    ]
